FROM golang:1.23.3-alpine

WORKDIR /app

RUN apk add --no-cache git

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN go build -o feed-sender ./feed_sender/feed_sender.go

CMD ["./feed-sender"]