FROM golang:1.23.3-alpine

WORKDIR /app

RUN apk add --no-cache git

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN go build -o feed-worker ./feed_worker/feed_worker.go

CMD ["./feed-worker"]