global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

rule_files:
  - rules/*.yml

scrape_configs:
  - job_name: 'feed-sender'
    static_configs:
      - targets: ['feed-sender:8080']
    metrics_path: /health
    scrape_interval: 10s

  - job_name: 'feed-worker'
    metrics_path: /health
    scrape_interval: 10s
    dns_sd_configs:
      - names:
          - feed-worker
        type: A
        port: 8090

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']
    metrics_path: /metrics
    scrape_interval: 10s