groups:
  - name: feed_sender
    rules:
      - alert: FeedSenderUnhealthy
        expr: |
          feed_sender_healthy == 0
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "Feed Sender is unhealthy"
          description: "Feed Sender health check has been failing for more than 2 minutes"

      - alert: FeedSenderNoUpdates
        expr: |
          time() - feed_sender_last_successful_run_timestamp_seconds > 1800 # 30 minutes
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Feed Sender not updating"
          description: "Feed Sender hasn't successfully run in the last 30 minutes"

  - name: feed_worker
    rules:
      - alert: FeedWorkerUnhealthy
        expr: feed_worker_healthy == 0
        for: 30m
        labels:
          severity: warning
        annotations:
          summary: "Feed Worker is unhealthy"
          description: "Feed Worker instance {{ $labels.instance }} health check has been failing for more than 30 minutes"

      - alert: AllFeedWorkersUnhealthy
        expr: sum(feed_worker_healthy) == 0
        for: 30m
        labels:
          severity: critical
        annotations:
          summary: "All Feed Workers are unhealthy"
          description: "All Feed Worker instances are failing health checks for more than 30 minutes"

      - alert: FeedWorkerHighErrorRate
        expr: rate(feed_worker_errors_total[5m]) > 0.1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Feed Worker experiencing high error rate"
          description: "Feed Worker instance {{ $labels.instance }} has been experiencing a high error rate in the last 5 minutes"

      - alert: AllFeedWorkersHighErrorRate
        expr: sum(rate(feed_worker_errors_total[5m])) / count(rate(feed_worker_errors_total[5m])) > 0.1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "All Feed Workers experiencing high error rate"
          description: "All Feed Worker instances have been experiencing a high average error rate in the last 5 minutes"

      - alert: FeedWorkerStalled
        expr: rate(feed_worker_processed_feeds_total[2h]) == 0
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Feed Worker not processing feeds"
          description: "Feed Worker instance {{ $labels.instance }} hasn't processed any feeds in the last 2 hours"

      - alert: AllFeedWorkersStalled
        expr: sum(rate(feed_worker_processed_feeds_total[2h])) == 0
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "All Feed Workers stalled"
          description: "None of the Feed Worker instances have processed any feeds in the last 2 hours"
