groups:
  - name: feed_sender
    rules:
      - alert: FeedSenderUnhealthy
        expr: |
          feed_sender_healthy == 0
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "Feed Sender is unhealthy"
          description: "Feed Sender health check has been failing for more than 2 minutes"

      - alert: FeedSenderNoUpdates
        expr: |
          time() - feed_sender_last_successful_run_timestamp_seconds > 1800 # 30 minutes
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Feed Sender not updating"
          description: "Feed Sender hasn't successfully run in the last 30 minutes"

      - alert: FeedWorkerUnhealthy
        expr: feed_worker_healthy == 0
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "Feed Worker is unhealthy"
          description: "Feed Worker health check has been failing for more than 2 minutes"

      - alert: FeedWorkerHighErrorRate
        expr: rate(feed_worker_errors_total[5m]) > 0.1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Feed Worker experiencing high error rate"
          description: "Feed Worker has been experiencing a high error rate in the last 5 minutes"

      - alert: FeedWorkerStalled
        expr: rate(feed_worker_processed_feeds_total[15m]) == 0
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Feed Worker not processing feeds"
          description: "Feed Worker hasn't processed any feeds in the last 15 minutes"